# Copyright 2026 Canonical Ltd.  This software is licensed under the
# GNU Affero General Public License version 3 (see the file LICENSE).

from typing import Union

from pydantic import Field

from maasservicelayer.models.base import ResourceBuilder, UNSET, Unset


class OpenFGATupleBuilder(ResourceBuilder):
    """Autogenerated from utilities/generate_builders.py.

    You can still add your custom methods here, they won't be overwritten by
    the generated code.
    """

    object_id: Union[str, Unset] = Field(default=UNSET, required=False)
    object_type: Union[str, Unset] = Field(default=UNSET, required=False)
    relation: Union[str, Unset] = Field(default=UNSET, required=False)
    user: Union[str, Unset] = Field(default=UNSET, required=False)
    user_type: Union[str, Unset] = Field(default=UNSET, required=False)

    @classmethod
    def build_user_is_group_member_tuple(
        cls, user_id: str, group_id: str
    ) -> "OpenFGATupleBuilder":
        return OpenFGATupleBuilder(
            user=f"user:{user_id}",
            user_type="user",
            relation="member",
            object_id=group_id,
            object_type="group",
        )

    @classmethod
    def build_user_is_system_admin_tuple(
        cls, user_id: str
    ) -> "OpenFGATupleBuilder":
        return OpenFGATupleBuilder(
            user=f"user:{user_id}",
            user_type="user",
            relation="admin",
            object_id="system",
            object_type="system",
        )

    @classmethod
    def build_group_is_system_admin_tuple(
        cls, group_id: str
    ) -> "OpenFGATupleBuilder":
        return OpenFGATupleBuilder(
            user=f"group:{group_id}#member",
            user_type="userset",
            relation="admin",
            object_id="system",
            object_type="system",
        )

    @classmethod
    def build_system_controls_pool_tuple(
        cls, pool_id: str
    ) -> "OpenFGATupleBuilder":
        return OpenFGATupleBuilder(
            user="system:system",
            user_type="user",
            relation="system",
            object_id=pool_id,
            object_type="pool",
        )

    @classmethod
    def build_user_is_pool_user_tuple(
        cls, user_id: str, pool_id: str
    ) -> "OpenFGATupleBuilder":
        return OpenFGATupleBuilder(
            user=f"user:{user_id}",
            user_type="user",
            relation="user",
            object_id=pool_id,
            object_type="pool",
        )

    @classmethod
    def build_group_is_pool_user_tuple(
        cls, group_id: str, pool_id: str
    ) -> "OpenFGATupleBuilder":
        return OpenFGATupleBuilder(
            user=f"group:{group_id}#member",
            user_type="userset",
            relation="user",
            object_id=pool_id,
            object_type="pool",
        )

    @classmethod
    def build_user_is_pool_auditor_tuple(
        cls, user_id: str, pool_id: str
    ) -> "OpenFGATupleBuilder":
        return OpenFGATupleBuilder(
            user=f"user:{user_id}",
            user_type="user",
            relation="auditor",
            object_id=pool_id,
            object_type="pool",
        )

    @classmethod
    def build_group_is_pool_auditor_tuple(
        cls, group_id: str, pool_id: str
    ) -> "OpenFGATupleBuilder":
        return OpenFGATupleBuilder(
            user=f"group:{group_id}#member",
            user_type="userset",
            relation="auditor",
            object_id=pool_id,
            object_type="pool",
        )

    @classmethod
    def build_user_is_pool_operator_tuple(
        cls, user_id: str, pool_id: str
    ) -> "OpenFGATupleBuilder":
        return OpenFGATupleBuilder(
            user=f"user:{user_id}",
            user_type="user",
            relation="operator",
            object_id=pool_id,
            object_type="pool",
        )

    @classmethod
    def build_group_is_pool_operator_tuple(
        cls, group_id: str, pool_id: str
    ) -> "OpenFGATupleBuilder":
        return OpenFGATupleBuilder(
            user=f"group:{group_id}#member",
            user_type="userset",
            relation="operator",
            object_id=pool_id,
            object_type="pool",
        )
