// Copyright (c) 2025 Canonical Ltd
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

package main

import (
	"encoding/csv"
	"errors"
	"flag"
	"fmt"
	"io"
	"os"
	"text/template"
)

const (
	tmpl = `
// Generated by generate-mac-prefixes, do not edit
package {{ .Package }}

import (
	radix "github.com/armon/go-radix"
)

var (
	MACPrefixes = map[string]interface{
	{{range .Entries}}
		"{{ .Assignment }}": "{{ .Organization }}",
	{{end}}
	}

	MACPrefixRadix = radix.NewFromMap(MACPrefixes)
)
`
)

var (
	inputFile  string
	outputFile string
	tgtPackage string
)

type macEntry struct {
	Registry     string
	Assignment   string
	Organization string
	Address      string
}

func parseEntries(f io.Reader) ([]macEntry, error) {
	reader := csv.NewReader(f)

	columns, err := reader.Read()
	if err != nil {
		if errors.Is(err, io.EOF) {
			return []macEntry{}, nil // do not fail, no-op instead
		}

		return nil, err
	}

	var entries []macEntry

	for {
		row, err := reader.Read()
		if err != nil {
			if errors.Is(err, io.EOF) {
				break
			}

			return nil, err
		}

		var entry macEntry

		for i, col := range columns {
			switch col {
			case "Registry":
				entry.Registry = row[i]
			case "Assignment":
				entry.Assignment = row[i]
			case "Organization Name":
				entry.Organization = row[i]
			case "Organization Address":
				entry.Address = row[i]
			}
		}

		entries = append(entries, entry)
	}

	return entries, nil
}

type templateData struct {
	Package string
	Entries []macEntry
}

func writeGoFile(entries []macEntry) error {
	var err error

	t := template.New("macprefixes.go")

	t, err = t.Parse(tmpl)
	if err != nil {
		return err
	}

	f, err := os.OpenFile(outputFile, os.O_CREATE|os.O_RDWR, 0600)
	if err != nil {
		return err
	}

	defer f.Close()

	return t.Execute(f, templateData{
		Package: tgtPackage,
		Entries: entries,
	})
}

func run() int {
	flag.StringVar(&inputFile, "i", "MAC.CSV", "mac prefix csv file path")
	flag.StringVar(&outputFile, "o", "macprefixes.go", "output file path")
	flag.StringVar(&tgtPackage, "p", "dhcp", "targetted output package")

	flag.Parse()

	f, err := os.Open(inputFile)
	if err != nil {
		fmt.Println(err)
		return 1
	}

	defer f.Close()

	entries, err := parseEntries(f)
	if err != nil {
		fmt.Println(err)
		return 1
	}

	err = writeGoFile(entries)
	if err != nil {
		fmt.Println(err)
		return 1
	}

	return 0
}

func main() {
	os.Exit(run())
}
